In [1]:
import pandas as pd

In [2]:
raw_data = pd.read_csv('../data/flight_raw.csv', index_col='FL_DATE')
documentation_data = pd.read_csv('../data/Documentation.csv')

In [3]:
raw_data.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,OP_UNIQUE_CARRIER,OP_CARRIER,TAIL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,...,CANCELLATION_CODE,DIVERTED,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
FL_DATE,,,,,,,,,,,,,,,,,,,,,
12/1/2025 12:00:00 AM,2025,4,12,1,1,AA,AA,N101NN,12478,1247805,...,NaN,0.0,338.0,1.0,2475.0,NaN,NaN,NaN,NaN,NaN
12/1/2025 12:00:00 AM,2025,4,12,1,1,AA,AA,N101NN,12478,1247805,...,NaN,0.0,336.0,1.0,2475.0,NaN,NaN,NaN,NaN,NaN
12/1/2025 12:00:00 AM,2025,4,12,1,1,AA,AA,N101NN,12892,1289209,...,NaN,0.0,286.0,1.0,2475.0,NaN,NaN,NaN,NaN,NaN
12/1/2025 12:00:00 AM,2025,4,12,1,1,AA,AA,N102NN,12892,1289209,...,NaN,0.0,290.0,1.0,2475.0,352.0,0.0,0.0,0.0,0.0
12/1/2025 12:00:00 AM,2025,4,12,1,1,AA,AA,N102UW,10599,1059904,...,NaN,0.0,51.0,1.0,350.0,NaN,NaN,NaN,NaN,NaN

In [4]:
documentation_data

           SYS_FIELD_NAME                                         FIELD_DESC
0                    YEAR                                               Year
1                 QUARTER                                      Quarter (1-4)
2                   MONTH                                              Month
3            DAY_OF_MONTH                                       Day of Month
4             DAY_OF_WEEK                                        Day of Week
5                 FL_DATE                             Flight Date (yyyymmdd)
6       OP_UNIQUE_CARRIER  Unique Carrier Code. When the same code has be...
7              OP_CARRIER  Code assigned by IATA and commonly used to ide...
8                TAIL_NUM                                        Tail Number
9       ORIGIN_AIRPORT_ID  Origin Airport, Airport ID. An identification ...
10  ORIGIN_AIRPORT_SEQ_ID  Origin Airport, Airport Sequence ID. An identi...
11  ORIGIN_CITY_MARKET_ID  Origin Airport, City Market ID. City Market ID...
12                 ORIGIN                                     Origin Airport
13       ORIGIN_CITY_NAME                          Origin Airport, City Name
14       ORIGIN_STATE_ABR                         Origin Airport, State Code
15        ORIGIN_STATE_NM                         Origin Airport, State Name
16             ORIGIN_WAC                    Origin Airport, World Area Code
17        DEST_AIRPORT_ID  Destination Airport, Airport ID. An identifica...
18    DEST_AIRPORT_SEQ_ID  Destination Airport, Airport Sequence ID. An i...
19    DEST_CITY_MARKET_ID  Destination Airport, City Market ID. City Mark...
20                   DEST                                Destination Airport
21         DEST_CITY_NAME                     Destination Airport, City Name
22         DEST_STATE_ABR                    Destination Airport, State Code
23          DEST_STATE_NM                    Destination Airport, State Name
24               DEST_WAC               Destination Airport, World Area Code
25           CRS_DEP_TIME              CRS Departure Time (local time: hhmm)
26               DEP_TIME           Actual Departure Time (local time: hhmm)
27               TAXI_OUT                          Taxi Out Time, in Minutes
28             WHEELS_OFF                 Wheels Off Time (local time: hhmm)
29              WHEELS_ON                  Wheels On Time (local time: hhmm)
30                TAXI_IN                           Taxi In Time, in Minutes
31               ARR_TIME             Actual Arrival Time (local time: hhmm)
32              CANCELLED                 Cancelled Flight Indicator (1=Yes)
33      CANCELLATION_CODE              Specifies The Reason For Cancellation
34               DIVERTED                  Diverted Flight Indicator (1=Yes)
35               AIR_TIME                            Flight Time, in Minutes
36                FLIGHTS                                  Number of Flights
37               DISTANCE                  Distance between airports (miles)
38          CARRIER_DELAY                          Carrier Delay, in Minutes
39          WEATHER_DELAY                          Weather Delay, in Minutes
40              NAS_DELAY              National Air System Delay, in Minutes
41         SECURITY_DELAY                         Security Delay, in Minutes
42    LATE_AIRCRAFT_DELAY                    Late Aircraft Delay, in Minutes

In [ ]:
useful_columns = [
    "FL_DATE", "OP_CARRIER", "OP_CARRIER_NAME", "OP_CARRIER_FL_NUM" ,"ORIGIN,ORIGIN_CITY_NAME",
    "DEST", "DEST_CITY_NAME", "CRS_DEP_TIME", "DEP_TIME", "DEP_DELAY", "TAXI_OUT", "TAXI_IN",
    CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,CANCELLATION_REASON,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,MAINTENANCE_RELATED,TURNAROUND_TIME_MIN,PAX_COMPENSATION_USD,IS_DELAYED,DELAY_CATEGORY
]

pandas.DataFrame